
spring:
  datasource:
    url:
      jdbc: h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: embedded
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true

server:
  port: 80
